###########################
# Plugin made by:         #
# Jona / Pottenmaker      #
# Dicord: Jona#7797       #
# Open for new            #
# challanges!             #
# This plugin is made for #
# fun, so respect it!     #
###########################

#Prefix of the messages.
Prefix: '&c&lTeams &8&l> &7'

#Configurations about the people with no team.
NoTeam_Name: 'No-Team'
NoTeam_Prefix: '&cNo-Team'
NoTeam_Role: 'None'
NoTeam_Role_Prefix: '&7'

#Configurations about the NameTag+Tab of players.
Use_Tab: false

#Chat configurations.
Use_Chat_System: true
Global_Chat_Format: '&c[G] &7[%t_color%%TeamP_teamprefix%&7] %TeamP_role_prefix% &7%player%: &f%message%'
Team_Chat_Format: '&a[T] %TeamP_role_prefix% &7%player%: &a%message%'

#Channel prefixes:
Global_Letter: '!'

#The default role/rank that everyone gets when they join a team.
Member_Rank: 'Member'

#The rank the player gets when creating a team, the leader rank.
Leader_Rank: 'Leader'

#The rank you get when passing someone other the leadership.
CoLeader_Rank: 'CoLeader'

#This section is about the color's that will be displayed in chat when a specific team chats.
#The placeholder: %t_color% can be used for this in the chat config section. THIS ONLY WORKS FOR GLOBAL CHAT!!!!!
Ally_Color: '&d' #The color of the prefix of your alliance.
Team_Color: '&6' #The color of the prefix of your teammates.
Other_Color: '&7' #The color of the prefix of players that aren't of your or aren't a ally.