name: TeamPlugin
version: ${project.version}
main: nl.snowpix.teamplugin.TeamPlugin
api-version: 1.16
authors: [ Pottenmaker ]
description: TeamPlugin of Empalis.
website: www.snowpix.nl
commands:
  teams:
    description: The main command for the teams plugin.
    aliases: [team]
