###########################
# Plugin made by:         #
# Jona / Pottenmaker      #
# Dicord: Jona#7797       #
# Open for new            #
# challanges!             #
# This plugin is made for #
# fun, so respect it!     #
###########################

# ! * PLUGINS NEEDED/DEPENDENCY(S): PlaceholderAPI, WGEvents, WorldGuard, WorldEdit.

#***************************************************************************************#
# !> MAIN OPTIONS, NO SPECIAL CATEGORY *
#
# HERE YOU CAN CHANGE THE MAIN OPTIONS OF THE PLUGIN. *
# TO CHANGE THE MESSAGES OF COMMANDS OR OTHER THINGS, GO TO THE FILE 'messages.yml' *
# Note that the maker his language is Dutch so some words can be in Dutch, but..
# you can change that! File: 'messages.yml' !
#
#
# *! I ADVICE YOU TO NOT RELOAD YOUR SERVER SO THE DATA CAN LOAD UP SLOWLY !*
#
#
#***************************************************************************************#

#The prefix of the messages.
Prefix: '&4&lPrefix &8&l> &7'

#Options for people that are new or haven't joined a kingdom yet.
NoKingdom_Name: 'Kingdomloos'
NoKingdom_Prefix: '&7[&8Kingdomloos&7]'
NoKingdom_Display: '&8Kingdomloos'
NoKingdom_Tab: '&7[&8KDLOOS&7] &7'
NoKingdom_Rank: 'Geen'
NoKingdom_Rank_Prefix: '&7[Geen]'
NoKingdom_Rank_Display: '&7Geen'
NoKingdom_Soort: 'Mens'

#General Permissions:
Donator_Perm: 'kd.donator'
Staff_Perm: 'kd.staff'
Admin_Perm: 'kd.admin'

#The member rank of every kingdom, when a player joins he gets this rank.
# ! BE AWARE THAT THIS CAN BE CASE SENSITIVE (HOOFDLETTERGEVOELIG)!!
Member_Rank: 'Burger'

#Death messages:
#PlaceHolders that can be used for this message: %kingdomprefix_victim%, %kingdomdisplay_victim%, %rankdisplay_victim%, %rankprefix_victim%, %victim%, %attacker%.
#You can change 'victim' to 'attacker' in the placeholders. Example: %kingdomprefix_attacker%.
DeathMessage: '%kingdomprefix_victim% &f%victim% &7is verwond door %kingdomprefix_attacker% &f%attacker%&7!'
DeathMessage_Other: '%kingdomprefix_victim% &f%victim% &7is doodgegaan!' #-> If the death is not caused by a player this will be the message!

#Options for the /k info command.
See_King_Info: true
King_Role: 'Koning' #!* BE AWARE THAT THIS CAN BE CASE SENSITIVE! (HOOFDLETTERGEVOELIG)
Info_Message: '&8> &7Online: &f(&6%count_members%&f) &f> &2%members%..'
King_Line: '&8> &6Koning&7: &f%king%' #ONLY ENABLED IF SEE_KING_INFO IS TRUE NOT FALSE !

#Options for /k spawn.
SpawnTime: 100 #NOTE THAT THIS IS IN TICKS, 1 SECOND = 20 ticks. ( for example 5 seconds is 100 ticks 5x20=100).
Spawned_Message: '&aJe bent succesvol geteleporteerd naar je kingdom spawn!'
SpawnTimer_Message: '&7Je word over &85 &7seconden naar je spawn teleporteerd..'
SpawnTimer_Already: '&cJe teleportatie is al bezig..'
SpawnTimer_Move: '&cDoor te bewegen heb je de teleportatie geannuleerd..'
SpawnNotExist: '&cJe spawn moet nog neergezet worden of bestaat niet.'
SpawnOnDeath: true

#Actions that need to be executed when a player leaves a kingdom or gets kicked. (Via console)
Commands_Leave:
  - 'spawn %player%'
  - 'broadcast %player% is gekickt'


#***************************************************************************************#
# !> REGION ENTER OPTIONS *
#
# > You can set this option to false if you don't want to use it.
# > Returning it to false or true, not an other option.
#***************************************************************************************#

#Do you want to use the options below? (true/false)
UseRegionEvents: true

#The options for entering a kingdom region.
MessageOnEveryRegion: false # -> If you put this to true the regions that are not from kingdoms will give a message too.
RegionEnter: '&6* &fJe hebt nu &2%region% &fbetreden! &6*'
RegionEnter_Title: '&2&l%region%'
RegionEnter_SubTitle: '&fJe hebt nu &2%region% &fbetreden!'
RegionLeave: '&6* &fJe hebt nu &2%region% &fverlaten. &6*'
RegionLeave_Title: '&2&l%region%'
RegionLeave_SubTitle: '&fJe hebt nu &2%region% &fverlaten!'
#Own Kingdom enter options.
OwnKingdomRegionEnter: '&6* &fJe hebt nu jouw kingdom &2%region% &fbetreden! &6*'
OwnKD_Region_EN_TITLE: '&2&l%region%'
OwnKD_Region_EN_SUBTITLE: '&fJe hebt je kingdom betreden!'
OwnKingdomRegionLeave: '&6* &fJe hebt nu jouw kingdom &2%region% &fverlaten! &6*'
OwnKD_Region_LE_TITLE: '&2&l%region%'
OwnKD_Region_LE_SUBTITLE: '&fJe hebt je kingdom verlaten!'

#The name that will be given when a player is not in an location:
Wilderniss_Name: '&fWildernis'


#***************************************************************************************#
# !> CHANNEL / CHAT SETTINGS *
#
# HERE YOU CAN CHANGE THE CHANNELS OR CHAT FORMATS! *
# Note that for placeholders only PlaceHolderAPI is supported! *
#
# Placeholders: %kd_kingdomprefix%, %kd_rankprefix%, %kd_rank%..
# %kd_kingdomdisplay%, %kd_kingdom%, %kd_tab%, %kd_soort%..
# %kd_rankdisplay% %kd_locatie%.
#
#***************************************************************************************#

#If you turn this option to false, it will turn the whole chat system of this plugin off. Options: 'true / false'.
Use_Chat: true

#KINGDOM CHAT -> This message goes to the players that are in the same kingdom.
kingdom_format: '&8[&7KD&8] &7%kd_kingdomprefix% %kd_rankprefix% &7%player%&f: &7%message%'

#PUBLIC CHAT -> This message is public so everyone can see it.
public_letter: '!'
public_format: '&8[G] &7%kd_kingdomprefix% %kd_rankprefix% &7%player%&f: &7%message%'

#ROLEPLAY CHAT -> This is a channel for players to roleplay.
roleplay_letter: '#'
roleplay_format: '&f[RP] &7%kd_kingdomprefix% %kd_rankprefix% &7%player%&f: &f%message%'
roleplay_channel_perm: 'kingdom.roleplay'

#Staff chat NOTE: THIS CHANNEL IS PUBLIC IT IS JUST USED AS EEN BROADCAST/SHOUT!:
staff_letter: '*'
staff_format: '&7[&3&lSTAFF&7] &f%player%&f: &f%message%'
staff_channel_perm: 'kingdom.staff'


#*************************************************************************************************#
# !> JOIN AND LEAVE EVENTS!
#
# HERE YOU CAN CHANGE THE MESSAGES OR OTHER STUFF FOR THINGS WHEN PLAYERS ARE JOINING OR QUITING. *
# NOTE THAT FOR THIS ONE PLACEHOLDERS CAN ONLY BE USED IN THE JOIN MESSAGE NOT THE LOGINMESSAGE. *
# PlaceHolderAPI is the only api for placeholders that can be used for this version. *
#
#*************************************************************************************************#

#When a player joins the server this message wil come up in the player's chat. (PlaceholderAPI can be used in this message)
JoinMessage:
  - '&7'
  - '&7Welkom terug op de &c&lKingdom &7server!'
  - '&7'

#*************************************************************************************************#
# !> SCOREBOARD
#
# HERE YOU CAN CHANGE THE SCOREBOARD FOR PLAYERS *
# NOT THAT PLACEHOLDERAPI IS NEEDED FOR THIS! *
# PlaceHolderAPI is the only api for placeholders that can be used for this version. *
#
# Placeholders: %kd_kingdomprefix%, %kd_rankprefix%, %kd_rank%..
# %kd_kingdomdisplay%, %kd_kingdom%, %kd_tab%, %kd_soort%..
# %kd_rankdisplay% %kd_locatie%.
#
#*************************************************************************************************#

#Do you want to use the scoreboard of this plugin or not? (true/false)
Use_Scoreboard: true

#Scoreboard normal:
n_Scoreboard_Title: '&6&lKingdom'
n_Scoreboard_Lines:
  - ''
  - '&eKingdom&7:'
  - ' &7%kd_kingdomprefix%'
  - ''
  - '&eRank&7:'
  - ' &7%kd_rankdisplay%'
  - ''
  - '&ePoints &8> &a%kd_points%'
  - '&eLocation&7:'
  - ' &7%kd_locatie%'
  - ''
  - '&6play.jouwplugin.nl'

#Scoreboard war:
w_Scoreboard_Title: '&c&lWORLD WAR'
w_Scoreboard_Lines:
  - ''
  - '&eTime&7:'
  - ' &7%timer%'
  - ''
  - '&eKills&7:'
  - ' %kingdoms%'
  - ''
  - '&6play.jouwplugin.nl'

#When filling in %kingdoms% there will be a format like: Kingdom: 2.
Kingdom_Format_War: '&7: &6%kills%'

#Timer for WorldWar:
w_Use_Timer: true #-> Setting this to false will disable the %timer% placeholder.
Timer_Seconds: 10000 #-> When these seconds have passed, the world war will be over.

#***************************************************************************************#
# !> INFLUENCE / POINTS SYSTEM *
#
# > You can set this option to false if you don't want to use it.
# > Returning it to false or true, not an other option.
#***************************************************************************************#

#If you want to use points/influence (true) not want to use it? (false).
Use_Points_System: true

#If you turn this to 'true' allies can break and bypass points/influence.
Allies_Bypass: true

#The costs of points/influence. ( !* ONLY CHANGE THE NUMBERS!!! *! )

Points_Cost:
  Breaks:
    Chest: 200
    TrappedChest: 150
    Beacon: 200
    DiamondBlock: 100
    Other: 50
  Place:
    Bucket: 0 #-> If you set this to 0 it will be disabled.
    TNT: 250
    Obsidian: 100
    Enderchest: 100
    Other: 25
  Use:
    Chest: 120
    TrappedChest: 100
    Enderchest: 40
    Door: 50
    Fence_Gate: 50
    Trapdoor: 50
    Other: 30

#The points/influence a player gets every 5 minutes:
Bounty_Seconds: 15 #-> The points/influence a player gets if the bounty is true.
Use_Bounty: true

#The amount of points/influence that is making the Bounty stop.
Max_Points: 2000


#***************************************************************************************#
# !> MINEISLAND SYSTEM *
#
# > You can set this option to false if you don't want to use it.
# > Returning it to false or true, not an other option.
# Permissions: mineisland.use, mineisland.define, mineisland.remove, mineisland.reload.
# mineisland.bypass -> If Block unwanted break is true you can bypass it via this.
#***************************************************************************************#

#Do you want to use the mineisland system? no = false - yes = true.
Use_Mineisland: true

#The respawn time of different ores.
Respawn:
  coal_ore: 60
  iron_ore: 90
  gold_ore: 120
  lapis_ore: 120
  redstone_ore: 120
  diamond_ore: 300
  emerald_ore: 300

#Do you want to send a message and cancel the event when a incorrect block is broken?
Block_unwanted_break: false
Block_unwanted_break_message: '&4&lHey! &r&7Sorry, je kan alleen ores slopen hier!'


#**************************************************************************************************************#
# *! -> Permissions of the plugin! *!
# *! -> Permissions that can be set in ranks.yml: kingdom.setrank, kingdom.invite, kingdom.kick, kingdom.leave.
# *! -> kingdom.ally, kingdom.neutral, kingdom.setspawn, kingdom.join, kingdom.spawn, kingdom.tphere.
#**************************************************************************************************************#
# *! -> Permissions that need to be set with plugins like LuckPerms or PermissionsEx: *!
# kingdom.set, kingdom.colorchat, (Permissions for channels), kingdom.create, kingdom.mutechannel
# points.use, points.give, points.set, points.bypass, kingdom.delete, edit.admin.
# !!!! POINTS.USE GIVES YOU THE PERMISSION TO ACCESS THE /POINTS HELP!!!
#**************************************************************************************************************#
# *! -> I recommend to use the Perm plugin 'LuckPerms', PermissionsEx also. *!
#**************************************************************************************************************#