name: Kingdom
version: 1.3
main: nl.snowpix.kingdom.Kingdom
authors: [ Pottenmaker ]
description: De enige echte Kingdom plugin!
softdepend: [PlaceholderAPI, WorldGuardEvents, WorldGuard, WorldEdit]
api-version: 1.16
commands:
  staff:
    description: Go into staffmode or vanishmode! (Player)
    aliases: [mode, staffmode, vanish, v]
  kingdom:
    description: The main kingdom command. (Player)
    aliases: [kingdoms, k, kd]
  edit:
    description: For editing kingdoms. (Console, Player)
  tl:
    description: Send people of your kingdom your location. (Player)
    aliases: [location]
  points:
    description: The main points/influence command. (Console, Player)
    aliases: [influence]
  mineisland:
    description: The main mineisland command. (Console, Player)
    aliases: [mineis]
